apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - name: myapp-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001

